FROM quay.io/gravitational/teleport:3.2.4

LABEL image=codejamninja/teleport:latest \
  maintainer="Jam Risser <jam@codejam.ninja>" \
  base=ubuntu

RUN apt-get update && apt-get install -y \
  curl \
  git \
  unzip \
  vim \
  zip \
  zsh
